insert into etudiant values(1, 'Rocchi', 'Stephane', '', '13008', 'Marseille', 1, 1);
insert into etudiant values(2, 'Martin', 'Martine', '', '13002', 'Marseille', 1, 1);
insert into etudiant values(3, 'Pavia', 'Franck', '', '34000', 'Beziers', 1, 2);
insert into etudiant values(4, 'Mercury', 'Serge', '', '43000', 'Clermont', 1, 2);
insert into etudiant values(5, 'Monier', 'Marie', '', '13240', 'Mimet', 1, 3);
insert into etudiant values(6, 'Levy', 'Sandrine', '', '84000', 'Avignon', 1, 3);
insert into etudiant values(7, 'Delvart', 'Corinne', '', '13001', 'Marseille', 1, 4);
insert into etudiant values(8, 'Trinkl', 'Jean', '', '13002', 'Marseille', 1, 4);
insert into etudiant values(9, 'Mathieu', 'Christian', '', '83000', 'Toulon', 1, 5);
insert into etudiant values(10, 'Lyon', 'Philippe', '', '84020', 'Avignon', 1, 5);
insert into etudiant values(11, 'Bertone', 'Helene', '', '13004', 'Marseille', 1, 6);
insert into etudiant values(12, 'Jolliot', 'Valerie', '', '13090', 'Aix en Pce', 1, 6);
insert into etudiant values(13, 'Parlier', 'Michel', '', '13002', 'Marseille', 1, 1);
insert into etudiant values(14, 'Ciara', 'Monique', '', '13001', 'Marseille', 1, 4);
insert into etudiant values(15, 'Dumas', 'Sylvie', '', '13120', 'Aix en Pce', 1, 6);
insert into etudiant values(16, 'Arvor', 'Patrick', '', '13007', 'Marseille', 2, 1);
insert into etudiant values(17, 'Douste', 'Laurent', '', '13006', 'Marseille', 2, 1); 
insert into etudiant values(18, 'Paez', 'Annie', '', '13007', 'Marseille', 2, 2); 
insert into etudiant values(19, 'Ungaro', 'Julien', '', '13020', 'Aix en Pce', 2, 2); 
insert into etudiant values(20, 'Reveste', 'Olivier', '', '13040', 'Aix en Pce', 2, 3); 
insert into etudiant values(21, 'Nichilo', 'Claire', '', '84000', 'Avignon', 2, 3); 
insert into etudiant values(22, 'Ndoye', 'Catherine', '', '83000', 'Toulon', 2, 4); 
insert into etudiant values(23, 'Bellamy', 'Philippe', '', '13020', 'Aix en Pce', 2, 4); 
insert into etudiant values(24, 'Roccia', 'Noemie', '', '13100', 'Aix en Pce', 2, 5); 
insert into etudiant values(25, 'Dubois', 'Aline', '', '13090', 'Aix en Pce', 2, 5); 
insert into etudiant values(26, 'Darmon', 'Adrien', '', '13000', 'Marseille', 2, 6); 
insert into etudiant values(27, 'Louvin', 'Julie', '', '13040', 'Aix en Pce', 2, 6); 
insert into etudiant values(28, 'Lucas', 'Charles', '', '13008', 'Marseille', 2, 2); 
insert into etudiant values(29, 'Rolbert', 'Francoise', '', '13010', 'Aix en Pce', 2, 3); 
insert into etudiant values(30, 'Savini', 'Didier', '', '13100', 'Aix en Pce', 2, 5); 

insert into prof values(1, 'Bonastre', 'Richard', '', '13009', 'Marseille', NULL); 
insert into prof values(2, 'Gilles', 'Bernard', '', '13008', 'Marseille', NULL); 
insert into prof values(3, 'Bechet', 'Jean-Marc', '', '83000', 'Toulon', NULL); 
insert into prof values(4, 'Nocera', 'Philippe', '', '13008', 'Marseille', NULL); 
insert into prof values(5, 'Minault', 'Roger', '', '13100', 'Aix en Pce', NULL);
insert into prof values(6, 'Boitard', 'Didier', '', '83000', 'Toulon', NULL); 
insert into prof values(7, 'Laporte', 'Marc', '', '13100', 'Aix en Pce', NULL) ; 
insert into prof values(8, 'Raingeard', 'Odile', '', '13008', 'Marseille', NULL); 
insert into prof values(9, 'Besse', 'Yves', '', '13100', 'Aix en Pce', NULL); 
insert into prof values(10, 'Fanny', 'Marc', '', '13100', 'Aix en Pce', NULL); 

insert into matiere values( 'ANG', 'Anglais', 20, 18, 30, 10, 'Langues', 30, 40, 1 );
insert into matiere values( 'ALL', 'Allemand', 20, 12, 30, 10, 'Langues', 30, 40, NULL );
insert into matiere values( 'ESP', 'Espagnol', 20, 10, 30, 10, 'Langues', 30, 40, 2 );
insert into matiere values( 'BD', 'Bases de donnees', 40, 20, 60, 20, 'Informatique', 50, 60, 4 );
insert into matiere values( 'SI', 'Conception de SI', 40, 20, 60, 20, 'Informatique', 50, 60, 5 );
insert into matiere values( 'PRL', 'Prolog', 40, 20, 60, 20,'Informatique', 50, 60, 3 );
insert into matiere values( 'STA', 'Statistiques', 30, 15, 30, 15, 'Maths', 30, 20, 6);
insert into matiere values( 'ALG', 'Algebre', 30, 10, 30, 15, 'Maths', 30, 20, 6);
insert into matiere values( 'ANA', 'Analyse', 30, 15, 30, 15, 'Maths', 30, 20, 8);
insert into matiere values( 'COMP', 'Comptabilite', 20, 10, 20, 10, 'Gestion', 20, 20, 7);
insert into matiere values( 'FIN', 'Finance', 20, 10, 20, 10, 'Gestion', 20, 20, 7);
insert into matiere values( 'EXPE', 'Expression ecrite', 15, 5, 15, 10, 'Communication', 10, 20, 10);
insert into matiere values( 'EXPO', 'Expression orale', 15, 5, 15, 10, 'Communication', 10, 20, 10);

update prof set mat_spec='ANG' where num_prof=1; 
update prof set mat_spec='ESP' where num_prof=2; 
update prof set mat_spec='PRL' where num_prof=3; 
update prof set mat_spec='BD' where num_prof=4; 
update prof set mat_spec='SI' where num_prof=5;
update prof set mat_spec='STA' where num_prof=6; 
update prof set mat_spec='COMP' where num_prof=7; 
update prof set mat_spec='ANA' where num_prof=8; 
update prof set mat_spec='ALG' where num_prof=9; 
update prof set mat_spec='EXPE' where num_prof=10; 

update etudiant set ADR_ET='Residence Mozart' where NUM_ET=1;
update etudiant set ADR_ET='Residence du Lac' where NUM_ET=2;
update etudiant set ADR_ET='Residence Bel-air' where NUM_ET=3;
update etudiant set ADR_ET='Villa Mon reve' where NUM_ET=4;
update etudiant set ADR_ET='Les moulinsards' where NUM_ET=5;
update etudiant set ADR_ET='Boulevard Borgne' where NUM_ET=6;
update etudiant set ADR_ET='Allee des pins' where NUM_ET=7;
update etudiant set ADR_ET='Rue Agnet' where NUM_ET=8;
update etudiant set ADR_ET='Bastide Longue' where NUM_ET=9;
update etudiant set ADR_ET='Avenue Magne' where NUM_ET=10;
update etudiant set ADR_ET='Rue de la Mongolie' where NUM_ET=11;
update etudiant set ADR_ET='Rue claire' where NUM_ET=12;
update etudiant set ADR_ET='Impasse des moineaux' where NUM_ET=13;
update etudiant set ADR_ET='Allee des musiciens' where NUM_ET=14;
update etudiant set ADR_ET='Rue de la poste' where NUM_ET=15;
update etudiant set ADR_ET='Villa La mer' where NUM_ET=16;
update etudiant set ADR_ET='Villa Le bout du monde' where NUM_ET=17;
update etudiant set ADR_ET='Residence Pontier' where NUM_ET=18;
update etudiant set ADR_ET='Residence des magnolias' where NUM_ET=19;
update etudiant set ADR_ET='Boulevard de la republique' where NUM_ET=20;
update etudiant set ADR_ET='Impasse des goudes' where NUM_ET=21;
update etudiant set ADR_ET='Rue du port' where NUM_ET=22;
update etudiant set ADR_ET='Boulevard Hopital' where NUM_ET=23;
update etudiant set ADR_ET='Avenue de Maupassant' where NUM_ET=24;
update etudiant set ADR_ET='Parc des ecrivains' where NUM_ET=25;
update etudiant set ADR_ET='Allee des Belges' where NUM_ET=26;
update etudiant set ADR_ET='Lac des signes' where NUM_ET=27;
update etudiant set ADR_ET='Traverse Indochine' where NUM_ET=28;
update etudiant set ADR_ET='Rond Point Bonneveine' where NUM_ET=29;
update etudiant set ADR_ET='Cours Mirabeau' where NUM_ET=30;

update prof set ADR_PROF='Rue des Ormeaux' where NUM_PROF=1;
update prof set ADR_PROF='Avenue Mirabeau' where NUM_PROF=2;
update prof set ADR_PROF='Chemin du rousset' where NUM_PROF=3;
update prof set ADR_PROF='Les champs' where NUM_PROF=5;
update prof set ADR_PROF='Villa Tout va bien' where NUM_PROF=4;
update prof set ADR_PROF='Boulevard Albert' where NUM_PROF=6;
update prof set ADR_PROF='Allee majeure' where NUM_PROF=7;
update prof set ADR_PROF='Rue Agniol' where NUM_PROF=8;
update prof set ADR_PROF='Grande bastide' where NUM_PROF=9;
update prof set ADR_PROF='Avenue de la Marne' where NUM_PROF=10;

insert into notation values(1, 'ANG', 10, 12);
insert into notation values(2,'EXPO',12,14);
insert into notation values(20,'SI',10,7);
insert into notation values(28,'COMP',12,12);
insert into notation values(25,'ALG',1,10);
insert into notation values(3,'ANG',10,12);
insert into notation values(16,'FIN',16,17);
insert into notation values(17,'FIN',15,16);
insert into notation values(18,'FIN',18,19);
insert into notation values(3,'EXPO',9,5);
insert into notation values(10,'COMP',17,14);
insert into notation values(4,'EXPO',15,9);
insert into notation values(3,'ALL',12,14);
insert into notation values(2,'PRL',15,15);
insert into notation values(6,'ALL',11,15);
insert into notation values(9,'ALL',13,16);
insert into notation values(9,'PRL',20,20);
insert into notation values(13,'EXPE',12,14);
insert into notation values(25,'PRL',17,9);
insert into notation values(14,'EXPE',14,16);
insert into notation values(7,'COMP',17,18);
insert into notation values(29,'COMP',10,11);
insert into notation values(14,'COMP',14,20);
insert into notation values(30,'BD',11,13);
insert into notation values(6,'PRL',17,6);
insert into notation values(25,'SI',17,18);
insert into notation values(2,'STA',18,2);
insert into notation values(8,'STA',4,3);
insert into notation values(10,'STA',13,5);
insert into notation values(13,'STA',18,17);
insert into notation values(4,'PRL',1,2);
insert into notation values(26,'SI',16,15);
insert into notation values(27,'SI',14,13);
insert into notation values(22,'ALL',3,4);
insert into notation values(11,'ALG',10,15);
insert into notation values(4,'ANG',14,18);
insert into notation values(12,'ALG',18,16);
insert into notation values(15,'PRL',12,15);
insert into notation values(20,'PRL',13,17);
insert into notation values(15,'EXPE',15,17);
insert into notation values(1,'SI',9,8);

insert into enseignt values('ANG', 1, 1);
insert into enseignt values('ALG',1,1);
insert into enseignt values('PRL',7,6);
insert into enseignt values('ALL',2,3);
insert into enseignt values('ALG',1,25);
insert into enseignt values('ANG',1,2);
insert into enseignt values('EXPE',1,24);
insert into enseignt values('EXPO',7,2);
insert into enseignt values('ALG',5,5);
insert into enseignt values('ALL',7,30);
insert into enseignt values('ANG',1,28);
insert into enseignt values('BD',4,23);
insert into enseignt values('SI',2,20);
insert into enseignt values('FIN',3,17);
insert into enseignt values('PRL',6,15);
insert into enseignt values('SI',6,11);
insert into enseignt values('SI',6,1);
insert into enseignt values('SI',6,4);
insert into enseignt values('EXPO',7,3);
insert into enseignt values('ANG',10,15);
insert into enseignt values('EXPO',7,4);
insert into enseignt values('ALG',1,28);
insert into enseignt values('ALG',1,26);
insert into enseignt values('EXPE',7,8);
insert into enseignt values('SI',5,25);
insert into enseignt values('SI',6,26);
insert into enseignt values('SI',7,27);
insert into enseignt values('FIN',4,16);
insert into enseignt values('FIN',4,17);
insert into enseignt values('FIN',4,18);
insert into enseignt values('ALL',2,6);
insert into enseignt values('ALL',2,9);
insert into enseignt values('BD',4,30);
insert into enseignt values('COMP',7,7);
insert into enseignt values('COMP',1,29);
insert into enseignt values('COMP',3,14);
insert into enseignt values('PRL',3,15);
insert into enseignt values('PRL',3,20);
insert into enseignt values('PRL',3,25);
insert into enseignt values('ANG',10,10);
insert into enseignt values('EXPE',6,2);
insert into enseignt values('ANG',3,3);
insert into enseignt values('ALG',1,22);
insert into enseignt values('ALG',1,12);

commit;
